- id: '1552960646597'
  alias: Abajur Apaga 23:45
  trigger:
  - at: '23:45'
    platform: time
  condition: []
  action:
  - alias: ''
    data: {}
    service: light.turn_off
    entity_id: light.smart_97efb0
    
- id: '1552960832798'
  alias: Abajur Por do Sol
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.smart_97efb0

- id: '1553148207146'
  alias: Suite Persiana Abrir
  trigger:
  - payload: suite_persiana_abrir
    platform: mqtt
    topic: comandos
  condition: []
  action:
  - service: switch.broadlink_send_packet_192_168_1_150
    data:
      packet:
      - 6QCiAgQEBhEHBAQLqTAYCxgMDRYMFw0XGAsMGQoYDBcMGBcOFQ0KGQwZChgKGRYPCRkVDw+BBR8EHwgbBB4HHAccBx0IGhQRBxwHGwgbFQ8IGwgbCRoVAAFJmzMXDBYNCxgLGQoZFg0LGQoZCxkKGRYOFgwLGAsZCxkKGRcMCxgXDBcNFg4WDAsZFg0LGBcNCxgLGgkYCxkLGBcNChoKGAwXFw0LGQoYCxkWAAFJmzIXDBcNCxgMFw0XFwwLGQsYCxgLGBcNGAsLGQwWDBgLGRYMDBgXDBgLGAwXDAsYFw0LGBcMDBcMGAsYDBcMGBcMDBcMGAsYFwwMGAsYDBcYAAFHnDEYDBcMDBgLFw0XFw0LGAsYDBgLGBgLFwwMGAsYDBcMGBcMDRYYCxgMGQsWDAwZFgwMFxgMDRYMGQsXCxgMFxkKDRcMFwwYGAsMGAsZChgXAAFfny8ZDBYMCxgMFwwYGAsMFwwYDBcMFxgMGQoMFwwYDBcMFxgMDBcYCxgMFwwXDQsXGQsLGBcMDBgLGAwXDBgLGBcNCxgLGQsXGQsXDRYMFwwMAAFUnDEXDBcMDBgMFwwXGAwLGAwXDBgLGBgMGAoMGA0WDBgMFxcMDBcYDBcMFwwYCwwYFwwNFhgMCxkLFw4WCxgMFxgMCxgMFwwYFwwXDBkLFwwLAAFUnTAZCxgMCxcMGA0XFgwMGAwXDBcMGBcNFgwNFgwYCxgMFxkLCxgYCxkLGAsXDAwXGAwLGBcMDBkLFwwZChgNFhgLDBkKGAwXGAwYCxcMFw0LAAFTni8YDBgLDBgLGAwXGAsMGAwXDBkKGBcMFw0LGAsYDBcMGBcMDBkXDBYMFwwZCwsYFwwNFhgMDBcMFwwYDBcNFxcMDBcMGAsXGA0WDBcMGAwLAAXcDBgNFgwY

- id: '1553148444439'
  alias: Suite Persiana Fechar
  trigger:
  - payload: suite_persiana_fechar
    platform: mqtt
    topic: comandos
  condition: []
  action:
  - service: switch.broadlink_send_packet_192_168_1_150
    data:
      packet:
      - 6QCiAgwHBA0ECgQKnjAZDBcMCxcNFw0XFwsNFwwXDBcMGBcMFw0LGAsZCxgLGBcNChkXDRUQBqwEIQQfBAQEHgcaCBwHHBMSBhsIHBMQFA8JGgkaFQ8UAAFJmzQVDRYNChoLGAoZFwwLGQoZCxgLGRYNFg0LGQoZCxgMGBcNChgXDRcMFg0WDQsZFg4KGRYOCRkMFwsYCxkLGRYMCxkMFxcNFg0LGAwXFwwXAAFHnTIXDRYMDBkKGgkYFwwMGAsYDBgLGBcMFwwMGAsYDRgLFxcMCxgXDRcMFwwXDgsXGAsMFxgNChgLGAwYCxkKGBcNDBcLGBcNFwwMFw0YFgwXAAFHnTEXDBcOCxcMFwwZFgwLGAwYDBcLGBcMGAwLGAwXDBgNFhcMDBkXCxcMGAsYDAsYFwwNFxcMCxgMFw0YCxcNFxgMChgMFxkLFwwMFwwYFwwXAAFgnDIXDBcMDBgLFwwYFwwNFgwYDBcMFxgMFwwMFwwYCxgMFxgMDBcXDBgLGAwXDAwXGAwLGBcMDBgLGAwXDBgLGBcMDBcNGBcLFw0XDBcMDRYMAAFUmzMWDBcNDBYMGAwYGAoMFwwYDBcMFxkLFwwMGAsYDBgMFxcMDRcXDBcMFwwXDAwXGAwLGRcLDBgLGA0WDBgMGRYLDBgNFhkLFwwXDRYMDBgLAAFTnTEXDBkLCxgMFwwYGAsMFw0XCxgNFhgMGAsMFwwXDRcNFhgMCxgXDBgLGAwXDAsYGAwLGBgLDBcMGQoYDBcMGBcNCxcNFxcNFwwXDBcMCxkLAAFTnDEYDBcNCxcMGAsYFw0MFg0XDRcLGBcMGQoNFgwYCxgMGBcNChgXDBgNFgwXDQsYGAsLGBcMDBcMGAwYCxkKGBcMDBcNFxcMGQoYDRYMDBgLAAXcDBgLGAwY

- id: '1553148542838'
  alias: Suite Persiana Parar
  trigger:
  - payload: suite_persiana_parar
    platform: mqtt
    topic: comandos
  condition: []
  action:
  - data:
      packet:
      - 6QGEAwgbFg4UDxUOCRsJGhUPCRoKGhUOFQ8JGwkZChoKGQoaFg4VDwkZGAwWDQoaFg0WDgoZFw0KGQsZChkLGgkZCxkWDQsZFg4KGRYNCxkWcp0yCxkKGhYNFwwYDAoZCxkWDQsZCxkWDRYNCxkLGQoZCxkLGBgMFg0MGBYNFw0KGRcOFQ8JGRYNCxkLGAsZCxoJGQsYGA0KGBcNDBkVDQsZFkKbMgsZCxgXDRcNFw0KGQoZFw0LGAsZFg0XDQsYDRcLGQoZCxgXDRcNChkXDBcOChgXDRcNChkXDAsaChkKGQsZCxgMGRYMDBgYCwsZFwwLGhdxnTMKGAwYFw0WDRgMChkLGBcNDBcMGBcNFg0LGQsZChgMGQoZFg0XDAwYFwwXDQsYFw0XDAsZFwwMGAsYDRcLGQsYCxkWDQsZFw0KGRcMCxkXQZwxDBgLGBcNFw4VDQsZChkXDAsZCxgXDRgLCxkMFwsZCxgMGBcMFw0MFxcNFwwLGRcMFw4KGBcNCxgLGQsYCxkMFw0XFwwMGBcMDBgXDAwYF3GdMgwYCxgXDRcNFg0MFwwYFw0LGQoZFwwZCgwYDBgLGQsYCxgXDRcNCxgYCxcNCxgYDBcNCxgXDAwYCxoKGAwYCxkKGRcMDBkWDAwZFg0LGBdBnDILGAwYFw0WDRcOChgLGBkLCxgMGBcNFg0LGQsYCxkLGQsYFw0WDQwXFw0XDAwYGAsYDAsYFw4KGQsYDBgLGgoYCxkWDQsZFg0LGBcPCRgXc50xDRcLGRcMFw0WDQsYDBgXDQsYCxkWDhYNCxgMFwwYCxoKGBgMGAwKGBcNFw4KGBcOFQ0LGRYNCxkLGAsYDBgLGQsYFw0LGBcNCxkWDgoYF0CdMgsYDBgXDBcNGAsMGAsYFw0LGAwZFg0YCwsaChgLGQsYCxkXDBcMDRgWDRYNCxkXDRYOChkWDA0XCxoKGAsZCxgMGBcMCxkXDAwYFwwMGBdxnTILGQwXFw0XDBcNCxkLGBcMDBgNFhcNFwwMGAsZCxgLGQwXGAwXDAwYFwwXDQsZFg0XDA0YFgwNGAoYDBgMFwwYCxkYCwsZFwwMGBcMDBkXP50yDBcMGBcOFwsXDAsZCxkWDQsYDBgXDRYNDBkKGAsZCxgMGBcMFw0LGBcNFwwLGRgLGA0KGBcNCxgNFwsaChgLGQsYFw4KGBcNCxgXDQsYFwAF3AAAAAA=
    service: switch.broadlink_send_packet_192_168_1_150
    
- id: '1553317888613'
  alias: Varanda Persianas Todas Abrir
  trigger:
  - payload: open
    platform: mqtt
    topic: varanda/todas/set
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.varanda_persiana_abrir

- id: '1553317945238'
  alias: Varanda Persianas Todas Fechar
  trigger:
  - payload: close
    platform: mqtt
    topic: varanda/todas/set
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.varanda_persiana_fechar

- id: '1553318070847'
  alias: Varanda Persianas Todas Parar
  trigger:
  - payload: stop
    platform: mqtt
    topic: varanda/todas/set
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.varanda_persiana_abrir
