homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -23.63
  longitude: -46.6322
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr
    name: tempo
  - platform: broadlink
    host: 192.168.1.150
    mac: 'B3:43:0D:B6:03:93'
    monitored_conditions:
      - temperature


# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

light:
  - platform: mqtt
    unique_id: 'suite_cama'
    name: 'Cama'
    state_topic: 'Suite/cama/status'
    command_topic: 'Suite/cama/switch'
    optimistic: false
  - platform: mqtt
    name: 'Criado Amanda'
    unique_id: 'suite_criado_amanda'
    state_topic: 'Suite/amanda/status'
    command_topic: 'Suite/amanda/switch'
    optimistic: false
  - platform: mqtt
    name: 'Criado Marcelo'
    unique_id: 'suite_criado_marcelo'
    state_topic: 'Suite/marcelo/status'
    command_topic: 'Suite/marcelo/switch'
    optimistic: false
  - platform: mqtt
    name: 'TV'
    unique_id: 'suite_tv'
    state_topic: 'Suite/tv/status'
    command_topic: 'Suite/tv/switch'
    optimistic: false
  - platform: mqtt
    name: 'Geral'
    unique_id: 'suite_geral'
    state_topic: 'Suite/fita/status'
    command_topic: 'Suite/fita/switch'
    optimistic: false
  - platform: mqtt
    name: 'Corredor'
    unique_id: 'suite_corredor'
    state_topic: 'Suite/corredor/status'
    command_topic: 'Suite/corredor/switch'
    optimistic: false
  - platform: mqtt
    name: 'Cozinha'
    unique_id: 'cozinha_nicho'
    state_topic: 'cozinha/nicho/status'
    command_topic: 'cozinha/nicho/switch'
    optimistic: false
  - platform: mqtt
    name: 'Pia'
    unique_id: 'cozinha_pia'
    state_topic: 'cozinha/pia/status'
    command_topic: 'cozinha/pia/switch'
    optimistic: false


media_player:
  - platform: denonavr
    host: 192.168.1.190
    name: Denon AVR2313
    show_all_sources: False
    zones:
      - zone: Zone2
        name: Varanda

switch:
  - platform: broadlink
    host: 192.168.1.151
    mac: 34:EA:34:BD:D3:56
    type: sp2
    friendly_name: 'Abajur Mesa'

  - platform: broadlink
    host: 192.168.1.150
    mac: 'B3:43:0D:B6:03:93'
    timeout: 15
    switches:
      tv_lg:
        friendly_name: "LG Tv Power"
        command_off: 'JgBYAAABJpQSERQRFTUTERMRFBEUEBQRFDUUNhMREzYUNhQ2EjYTNhQQFBETExI2ExEUEhMRExITNRQ2EzYUERM2EzcSNhQ2EwAFHwABJUkVAAxCAAEnSRMADQU='
      abajur_buffet:
        friendly_name: "Abajur Buffet"
        command_off: '1wAeAgoJBQcEBgYOBAQSCwQEBgoHBQwLBQQECQQMBAQGBAQJCgsFBgUHBBIEBQsKBAkGBQQOBg8EIQQEBgQLBAQEBgcODQQFExoLBgYECAYHDAkXBAQECQQECgwFBQQOBAUKBgUJBDAGGgcKGAkZCBoIGwcZGgkWDQQdBR4EHhMNFg0EHgQcFg4EHRYMBB0FHwQeBRsHGhgLBRwGAAEFGwgZCAkaBhoIGgcaCRsXCBkKBxoIGgcaGQgaCQcaCBkZCAkZGQkJGQgZCRgJGgcbGQcJGQkAAQMbCBoGCxcKGAoXDBYKGBoIGgkHGggYChgbBhsHCRgLGBgJCRgaBwsYCBkLGAgYChgaBwoZCgABAR0GGgcKGAoYCRgLFwsWGgcbCAoXChcLFxoHGwcKFwoYGwcLFxsGChcKGAoXChkKFhwHCxYKqjMLBA4IHgUcBQsXCxYMFwoWDBYbBxsKBxcKGQkYGwYaCAkYCRkaCQcZGggJGAoYChcLGAoXGgcKGQoAAQAdBhwHCxcJFwsWDBYLFxsIGQcKFwsXChcbCBoHCRkLFhsHCRgbBwoYCRcLFwoYChgaCAkYCgABAh0EHQcIGQoXChgKFwoYGwYbBwoYCxcLFR0GGggJGAkYGgkJGBoHCxcKFwoXDBcJFxwGChgKAAECHgUbBgsYCRcLFwsWChcdBRsICQABREUEBwsGCgQGEgQLBwQFCwQFBARGBA4EAAXcGggZGQgJGRkJCQ=='

cover:
  - platform: template
    covers:
      varanda_persianas:
        friendly_name: "Todas"
        optimistic: true
        open_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/todas/set'
              payload: 'open'
        close_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/todas/set'
              payload: 'close'
        stop_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/todas/set'
              payload: 'stop'

      varanda_persiana_1:
        friendly_name: "Persiana 1"
        open_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/1/set'
              payload: 'open'
        close_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/1/set'
              payload: 'close'
        stop_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/1/set'
              payload: 'stop'

      varanda_persiana_2:
        friendly_name: "Persiana 2"
        open_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/2/set'
              payload: 'open'
        close_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/2/set'
              payload: 'close'
        stop_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/2/set'
              payload: 'stop'

      varanda_persiana_3:
        friendly_name: "Persiana 3"
        open_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/3/set'
              payload: 'open'
        close_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/3/set'
              payload: 'close'
        stop_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/3/set'
              payload: 'stop'

      varanda_persiana_4:
        friendly_name: "Persiana 4"
        open_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/4/set'
              payload: 'open'
        close_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/4/set'
              payload: 'close'
        stop_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/4/set'
              payload: 'stop'

      varanda_persiana_5:
        friendly_name: "Persiana 5"
        open_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/5/set'
              payload: 'open'
        close_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/5/set'
              payload: 'close'
        stop_cover:
          - service: mqtt.publish
            data:
              topic: 'varanda/5/set'
              payload: 'stop'

binary_sensor:
  - platform: mqtt
    name: "Porta Lavanderia"
    state_topic: "lavanderia/porta/state"
    payload_on: "open"
    payload_off: "closed"
    device_class: door
    off_delay: 10

